hospedaje/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from hospedaje import settings
from hospedajes_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hospedajes/', include('hospedajes_app.urls')),
    path('', views.index, name='index'),  # path para cuando tocas en 'view site' desde Django Administration
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL)

#  static nos va a permitir generar una nueva url en base a nuestro media url y media root.

hospedajes_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from hospedajes_app import views

app_name = 'hospedajes_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('new_property/', views.property_form, name='propertyForm'),
    path('new_tipoAula/', views.tipoAula_form, name='tipoAulaForm'),
    path('new_caracteristica/', views.caracteristica_form, name='caracteristicaForm'),
    path('new_capacidad/', views.capacidad_form, name='capacidadForm'),
    path('property/<int:property_id>/', views.view_property, name='property'),
    path('my_reservas/<int:property_id>/', views.reservaByProperty, name='reservaByProperty'),
    path('my_reservas/', views.my_reservas, name='myReservas'),

    # path('secret2/', views.SecretPage.as_view(), name='secret2'),

    # url(r'^alta_salon/$', login_required(ingresar_salon), name='altaSalon'),

]

hospedajes_app/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db import models


class Host(User):
    pass

    class Meta:
        verbose_name_plural = 'Hosts'


class Profile(models.Model):
    name = models.CharField(max_length=25)
    surname = models.CharField(max_length=25)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name + ", " + self.surname + "."

    class Meta:
        verbose_name_plural = "Profiles"


class TipoAula(models.Model):
    name = models.CharField(max_length=25, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'TiposAula'


class Caracteristica(models.Model):
    name = models.CharField(max_length=25, unique=True)
    className = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Caracteristicas'


class Capacidad(models.Model):
    name = models.CharField(max_length=25, unique=True)
    className = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Capacidades'


class Property(models.Model):
    pax = models.IntegerField()
    title = models.CharField(max_length=25)
    description = models.CharField(max_length=100, null=True)
    image = models.ImageField(null=True, blank=True)
    daily_import = models.FloatField()
    tipoAula = models.ForeignKey(TipoAula, on_delete=models.DO_NOTHING)
    caracteristicas = models.ManyToManyField(Caracteristica, blank=True)
    user = models.ForeignKey(Host, null=True, on_delete=models.SET_NULL)
    hora = models.TextField(max_length=13, null=True)

    def __str__(self):
        return self.title + ", " + self.description + "."

    class Meta:
        verbose_name_plural = 'Properties'


class Reserva(models.Model):  # Reserva
    profile = models.ForeignKey(Profile, on_delete=models.DO_NOTHING)
    total = models.FloatField(default=0)
    date = models.DateTimeField(null=True)
    property = models.ForeignKey(Property, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.profile.name + ", " + self.profile.surname + "."

    class Meta:
        verbose_name_plural = 'Reservas'


class CapacidadXProperty(models.Model):
    capacidad = models.ForeignKey(Capacidad, on_delete=models.DO_NOTHING)
    property = models.ForeignKey(Property, on_delete=models.DO_NOTHING)
    quantity = models.IntegerField()

    def __str__(self):
        return "CapacidadXProperty"

    class Meta:
        verbose_name_plural = 'CapacidadesXProperty'


class RentalDate(models.Model):
    property = models.ForeignKey(Property, on_delete=models.DO_NOTHING)
    reserva = models.ForeignKey(Reserva, null=True, blank=True, on_delete=models.DO_NOTHING)
    date = models.DateField()

    def __str__(self):
        return "RentalDate"

    class Meta:
        verbose_name_plural = 'RentalDates'

hospedajes_app/forms.py
from django import forms
from .models import Property, TipoAula, RentalDate, Caracteristica, Capacidad, Profile


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ('title', 'description', 'pax', 'daily_import', 'image', 'tipoAula', 'caracteristicas', 'user',)


class TipoAulaForm(forms.ModelForm):
    class Meta:
        model = TipoAula
        fields = ('name',)


class CaracteristicaForm(forms.ModelForm):
    class Meta:
        model = Caracteristica
        fields = ('name',)


class CapacidadForm(forms.ModelForm):
    class Meta:
        model = Capacidad
        fields = ('name', 'className',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('name', 'surname', 'email',)

hospedajes_app/views.py
from datetime import timezone, datetime, date

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login
from django.db.models import Count, Sum, QuerySet
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

from hospedajes_app.forms import TipoAulaForm, PropertyForm, CaracteristicaForm, CapacidadForm, ProfileForm
from hospedajes_app.models import Property, TipoAula, RentalDate, Caracteristica, Capacidad, CapacidadXProperty, Reserva, Profile, Host


def index(request):
    tiposAula = TipoAula.objects.all()
    properties = Property.objects.all()

    if request.method == 'POST':

        id_tipoAula = request.POST['tipoAula']
        cant_pax = int(request.POST['pax'])
        initDate = request.POST['initDate']
        hora = request.POST['hora']

        if id_tipoAula:
            tipoAula = TipoAula.objects.get(id=id_tipoAula)
            properties = properties.filter(tipoAula=tipoAula)

        if cant_pax >= 1:
            properties = properties.filter(pax__gte=cant_pax)

        prop = []
        if initDate:
            for property in properties:
                rd = RentalDate.objects.filter(property=property, date__gte=initDate)
                if len(rd)>0:
                 prop.append(property)
            properties = prop

        if hora:
            properties = properties.filter(hora=hora)


    return render(request, 'hospedajes_app/index.html', {'properties': properties, 'tiposAula': tiposAula})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)

            login(request, user)

            return redirect('../')
    else:
        form = UserCreationForm()

    return render(request, 'registration/signup.html', {'form': form})


@login_required
@staff_member_required
# @permission_required('hospedajes_app.propertyForm', login_url='login')
def property_form(request):
    tiposAula = TipoAula.objects.all()

    if request.method == 'POST':
        form = PropertyForm(request.POST, request.FILES)
        if form.is_valid():
            new_property = form.save()
            # return HttpResponseRedirect(reverse('hospedajes_app:propertyForm'))
    else:
        form = PropertyForm()

    return render(request, 'hospedajes_app/forms/property_form.html', {'tiposAula': tiposAula, 'form': form})


@login_required
@staff_member_required
def tipoAula_form(request):
    tiposAula = TipoAula.objects.all()

    if request.method == 'POST':
        form = TipoAulaForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = TipoAulaForm()

    return render(request, 'hospedajes_app/forms/tipoAula_form.html', {'tiposAula': tiposAula, 'form': form})


@login_required
@staff_member_required
def caracteristica_form(request):
    caracteristicas = Caracteristica.objects.all()

    if request.method == 'POST':
        form = CaracteristicaForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = CaracteristicaForm()

    return render(request, 'hospedajes_app/forms/caracteristica_form.html', {'caracteristicas': caracteristicas, 'form': form})


@login_required
@staff_member_required
def capacidad_form(request):
    capacidades = Capacidad.objects.all()

    if request.method == 'POST':
        form = CapacidadForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = CapacidadForm()

    return render(request, 'hospedajes_app/forms/capacidad_form.html', {'capacidades': capacidades, 'form': form})


def view_property(request, property_id):
    error = ''
    dateList = ''
    property = Property.objects.get(id=property_id)
    rentalDates = RentalDate.objects.filter(property_id=property_id, reserva_id=None)
    capacidades = CapacidadXProperty.objects.filter(property_id=property_id)
    caracteristicas = Caracteristica.objects.filter(property__pk=property_id)

    for d in rentalDates:
        dateList += str(d.date)

    if request.method == 'POST':
        datesSelected = request.POST['dates']
        total = request.POST['total']
        name = request.POST['name']
        surname = request.POST['surname']
        email = request.POST['email']

        if datesSelected and name and surname and email:
            datesSelected = datesSelected.split(", ")
            total = total[1:]

            try:
                profile = Profile.objects.get(email=email)
            except Profile.DoesNotExist:
                profile = Profile(name=name, surname=surname, email=email)
                profile.save()

            reserva = Reserva(profile=profile, total=total, date=datetime.now(), property=property)
            reserva.save()

            for d in rentalDates:
                if str(d.date) in datesSelected:
                    d.reserva = reserva
                    d.save(update_fields=['reserva'])

            return HttpResponseRedirect(reverse('hospedajes_app:index'))
        else:
            error = 'Debe completar todos los campos para confirmar la reserva!'

    return render(request, 'hospedajes_app/view_property.html', {'property': property, 'capacidades': capacidades, 'caracteristicas': caracteristicas, 'dateList': dateList, 'error': error})


@login_required
@staff_member_required
def my_reservas(request):

    properties = Property.objects.filter(user_id=request.user.id)

    return render(request, 'hospedajes_app/my_reservas.html', {'properties': properties})


@login_required
@staff_member_required
def reservaByProperty(request, property_id):

    property = Property.objects.get(id=property_id)
    rentalDates = RentalDate.objects.filter(property=property)
    reservas = Reserva.objects.filter(property=property)
    totalAmount = 0

    for b in reservas:
        totalAmount += b.total

    return render(request, 'hospedajes_app/reservaByProperty.html', {'property': property, 'rentalDates': rentalDates, 'totalAmount': totalAmount})




# class SecretPage(LoginRequiredMixin, TemplateView):
#    template_name = 'hospedajes_app/secret_page.html'

templates/hospedajes_app/base.html
{% load static %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="Content-Type" content="text/html">

        <title>{% block titulo %}Hospedajes Python{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <!-- Jquery -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" crossorigin="anonymous"></script>
        <!-- Para multidatesPicker-->
        <script type="text/javascript" src="{% static 'js/jquery-ui-1.11.1.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery-ui.multidatespicker.js' %}"></script>
        <link href="https://code.jquery.com/ui/1.12.1/themes/pepper-grinder/jquery-ui.css" rel="stylesheet"/>
        <link rel="stylesheet" href="{% static 'css/jquery-ui.multidatespicker.css' %}">
        <!-- Fin multidatesPicker -->
    </head>

    <body>

    <nav class="navbar navbar-expand-lg text-light bg-dark mb-4">

        <a class="navbar-brand" href="{% url 'hospedajes_app:index' %}">ACME-ETSII</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'hospedajes_app:index' %}">Inicio</a>
                </li>
                {% if user.is_authenticated %}
                    {% if user.is_superuser or user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'hospedajes_app:myReservas' %}">Reservas</a>
                        </li>
                        <li class="nav-item">
                            <!--    <a class="nav-link" href="#">Secret Page 2</a> -->
                        </li>
                    {% endif %}
                {% endif %}
            </ul>

            {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            {% if user.is_superuser or user.is_staff %}
                                <div class="dropdown-submenu pull-left"><a class="dropdown-item dropdown-toggle" data-toggle="dropdown" href="#">Altas</a>
                                    <ul class="dropdown-menu">
                                        <!--<a class="dropdown-item" href="{% url 'hospedajes_app:propertyForm' %}">Propiedad</a>-->
                                        <a class="dropdown-item" href="{% url 'hospedajes_app:tipoAulaForm' %}">Tipo Aula</a>
                                        <a class="dropdown-item" href="{% url 'hospedajes_app:caracteristicaForm' %}">Caracteristicas</a>
                                        <a class="dropdown-item" href="{% url 'hospedajes_app:capacidadForm' %}">Capacidades</a>
                                    </ul>
                                </div>
                                <a class="dropdown-item" href="{% url 'admin:index' %}">Administración</a>
                            {% endif %}

                            <a class="dropdown-item" href="{% url 'password_change' %}">Cambiar contraseña</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                        </div>
                    </li>
                </ul>
            {% else %}
                <form class="form-inline my-2 my-lg-0">
                    <a href="{% url 'login' %}" class="btn btn-outline-secondary">Iniciar sesión</a>
                    <a href="{% url 'hospedajes_app:signup' %}" class="btn btn-primary ml-2">Registarse</a>
                </form>
            {% endif %}
        </div>
    </nav>


    <div class="content container">
        <div class="row">
            <div class="col">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>


    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></link>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <script type="text/javascript" src="{% static 'js/js.js' %}"></script>

    </body>
</html>

templates/hospedajes_app/bookingByProperty.html
{% extends 'hospedajes_app/base.html' %}

{% block titulo %} {{ property.title }} {% endblock %}

{% block content %}

<h2>{{ property.title }}</h2>

<nav class="navbar navbar-expand-lg text-dark bg-light mb-4 mt-2">

    <p class="d-inline mr-2"><b>Precio Diario:</b> ${{property.daily_import}}</p>
    <p class="d-inline ml-2"><b>Total Recaudado:</b> <span class="text-success">${{totalAmount}}</span></p>

    <button type="button" class="btn btn-warning d-inline ml-auto" >
        <a href="{% url 'hospedajes_app:myBookings' %}">Volver</a>
    </button>
</nav>


<table class="table table-striped table-hover table table-responsive-sm">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Fecha Alquilada</th>
            <th scope="col">Pasajero</th>
            <th scope="col">Reservado el día</th>
            <th scope="col">Contacto</th>
        </tr>
    </thead>
    {% for rd in rentalDates %}
    <tr>
        <tbody>
        {% if rd.booking %}
            <td><p>{{ rd.date }}</p></td>
            <td><p>{{ rd.booking.profile.surname }}, {{ rd.booking.profile.name }}</p></td>
            <td><p>{{ rd.booking.date }}</p></td>
            <td><p>{{ rd.booking.profile.email }}</p></td>
        {% else %}
            <td><p class="text-danger">{{ rd.date }}</p></td>
            <td><p class="text-danger">VACANTE</p></td>
            <td><p class="text-danger">-----------</p></td>
            <td><p class="text-danger">-----------</p></td>
        </tbody>
    {% endif %}
    </tr>
    {% endfor %}
</table>

{% endblock %}

templates/hospedajes_app/index.html
{% extends "hospedajes_app/base.html" %}

{% block titulo %}Reserva de espacios{% endblock %}

{% block content %}

<h2 class="text-center">Espacios a reservar</h2><br/>
<h5 class="text-center">Debido al horario lectivo, cada aula solo se podrá reservar a una hora determinada. Pero gracias a 
    nuestra oferta de reservas, puede contar de cualquier tipo a cualquier hora. 
</h5>
<br>


<nav class="navbar navbar-expand-lg text-dark bg-light mb-4">

    <form method="post" class="" novalidate>
        {% csrf_token %}

        <div class="row">
            <div class="col-2">
                <label for="tipoAula" class="d-inline">Tipo de aula: </label>
                <select name="tipoAula" id="tipoAula" class="form-control d-inline">
                    <option value="">
                        Seleccione un tipo de aula
                    </option>
                    {% if tiposAula %}
                        {% for tipoAula in tiposAula %}
                            <option value="{{ tipoAula.id }}">
                                {{ tipoAula.name }}
                            </option>
                        {% endfor %}
                    {% endif %}
                </select>
            </div>

            <div class="col-2">
                <label for="pax" class="d-inline">Capacidad: </label>
                <input type="number" name="pax" id="pax" placeholder="0" value="0" min="0" class="form-control">
            </div>

            <div class="col-3">
                <label for="initDate" class="d-inline">Fecha:</label>
                <input type="date" name="initDate" id="initDate" class="form-control">
            </div>

            <div class="col-3">
                <label for="hora" class="d-inline">Hora:</label>
                <input type="text" name="hora" placeholder="08:00 - 09:00" class="form-control">
            </div>

            <div class="col-3" style="margin-top:21px;">
                <button type="submit" class="btn btn-warning">Filtrar</button>
                <button type="reset" class="btn btn-warning">Resetear</button>
            </div>

        </div>

    </form>
</nav>


<section class="row">
    {% if properties %}
    {% for p in properties %}
    <article class="col-4 mb-4">
        <div class="card">

            <img src="{{ p.image.url }}" width="100%" height="200px">

            <div class="card-body p-2">
                <h5 class="text-primary">{{ p.tipoAula }}</h5>
                <h4 class="text-dark">{{ p.title }}</h4>
                <p>{{ p.description }}</p>

                <div class="d-block-inline mt-2">
                    <div class="row">
                        <div class="col-8">
                            <p>Capacidad: {{ p.pax }}</p>
                            <p>{{ p.daily_import|floatformat:2 }} €/h</p>
                        </div>
                        <div class="col-4 mt-2">
                            <a class="btn btn-success float-right" href="{% url 'hospedajes_app:property' p.id %}"
                               class="btn btn-primary"> Ver más</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>
    {% endfor %}

    {% else %}

    <div class="col">
        <h3 class="text-center">No hay propiedades</h3>
    </div>

    {% endif %}
</section>

<!--
    <table class="table table-striped table-hover table table-responsive-sm">
        {% if properties %}
        <thead class="thead-dark">
            <tr>
                <th scope="col" >#</th>
                <th scope="col">Título</th>
                <th scope="col">Descripción</th>
                <th scope="col">Pasajeros</th>
                <th scope="col">Importe Diario</th>
                <th scope="col">Ciudad</th>
                <th scope="col">Imagen</th>
                <th scope="col">Detalles</th>
            </tr>
        </thead>
        <tbody>
            {% for p in properties %}
            <tr>
                <td>{{ p.id }}</td>
                <td>{{ p.title }}</td>
                <td>{{ p.description }}</td>
                <td>{{ p.pax }}</td>
                <td>{{ p.daily_import }}</td>
                <td>{{ p.city.name }}</td>
                <td><img src="{{ p.image.url }}" width="80"></td>
                <td><a href="{% url 'hospedajes_app:property' p.id %}" class="btn btn-primary"> Ver más</a></td>
            </tr>
            {% endfor %}
            {% else %}
                <h3>No hay propiedades</h3>
            {% endif %}
        </tbody>
    </table>
-->
{% endblock %}

templates/hospedajes_app/my_bookings.html
{% extends 'hospedajes_app/base.html' %}

{% block titulo %}Mis Reservas{% endblock %}


{% block content %}

<h2>Reservas</h2><br/>

<section class="row">
    {% if properties %}
    {% for p in properties %}
    <article class="col-4 mb-4">
        <div class="card">

            <img src="{{ p.image.url }}" width="100%" height="200px">

            <div class="card-body p-2">
                <h5 class="text-primary">{{ p.city }}</h5>
                <h4 class="text-dark">{{ p.title }}</h4>
                <p>{{ p.description }}</p>

                <div class="d-block-inline mt-2">
                    <div class="row">
                        <div class="col-8">
                            <p>{{ p.pax }} Huéspedes</p>
                            <p>${{ p.daily_import|floatformat:2 }} ARS por noche</p>
                        </div>
                        <div class="col-4 mt-2">
                            <a class="btn btn-success float-right" href="{% url 'hospedajes_app:bookingByProperty' p.id %}"
                               class="btn btn-primary"> Ver Reservas</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>
    {% endfor %}

    {% else %}

    <div class="col">
        <h3 class="text-center">No hay propiedades</h3>
    </div>

    {% endif %}
</section>

{% endblock %}

templates/hospedajes_app/my_reservas.html
{% extends 'hospedajes_app/base.html' %}

{% block titulo %}Mis Reservas{% endblock %}


{% block content %}

<h2>Reservas</h2><br/>

<section class="row">
    {% if properties %}
    {% for p in properties %}
    <article class="col-4 mb-4">
        <div class="card">

            <img src="{{ p.image.url }}" width="100%" height="200px">

            <div class="card-body p-2">
                <h5 class="text-primary">{{ p.tipoAula }}</h5>
                <h4 class="text-dark">{{ p.title }}</h4>
                <p>{{ p.description }}</p>

                <div class="d-block-inline mt-2">
                    <div class="row">
                        <div class="col-8">
                            <p>Capacidad: {{ p.pax }}</p>
                            <p>${{ p.daily_import|floatformat:2 }} €</p>
                        </div>
                        <div class="col-4 mt-2">
                            <a class="btn btn-success float-right" href="{% url 'hospedajes_app:reservaByProperty' p.id %}"
                               class="btn btn-primary"> Ver Reservas</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>
    {% endfor %}

    {% else %}

    <div class="col">
        <h3 class="text-center">No hay reservas</h3>
    </div>

    {% endif %}
</section>

{% endblock %}

templates/hospedajes_app/reservaByProperty.html
{% extends 'hospedajes_app/base.html' %}

{% block titulo %} {{ property.title }} {% endblock %}

{% block content %}

<h2>{{ property.title }}</h2>

<nav class="navbar navbar-expand-lg text-dark bg-light mb-4 mt-2">

    <p class="d-inline mr-2"><b>Precio Diario:</b> ${{property.daily_import}}</p>
    <p class="d-inline ml-2"><b>Total Recaudado:</b> <span class="text-success">${{totalAmount}}</span></p>

    <button type="button" class="btn btn-warning d-inline ml-auto" >
        <a href="{% url 'hospedajes_app:myReservas' %}">Volver</a>
    </button>
</nav>


<table class="table table-striped table-hover table table-responsive-sm">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Fecha Alquilada</th>
            <th scope="col">Pasajero</th>
            <th scope="col">Reservado el día</th>
            <th scope="col">Contacto</th>
        </tr>
    </thead>
    {% for rd in rentalDates %}
    <tr>
        <tbody>
        {% if rd.reserva %}
            <td><p>{{ rd.date }}</p></td>
            <td><p>{{ rd.reserva.profile.surname }}, {{ rd.reserva.profile.name }}</p></td>
            <td><p>{{ rd.reserva.date }}</p></td>
            <td><p>{{ rd.reserva.profile.email }}</p></td>
        {% else %}
            <td><p class="text-danger">{{ rd.date }}</p></td>
            <td><p class="text-danger">VACANTE</p></td>
            <td><p class="text-danger">-----------</p></td>
            <td><p class="text-danger">-----------</p></td>
        </tbody>
    {% endif %}
    </tr>
    {% endfor %}
</table>

{% endblock %}

templates/hospedajes_app/secret_page.html
{% extends 'hospedajes_app/base.html' %}

{% block content %}
  <p>This is a secret page!</p>
{% endblock %}